version: "3.7"

services:
  scraper:
    image: scrimage:latest
    environment:
      REST: 'locahost:8081'
    networks:
      hostnet: {}
    deploy:
      replicas: 1

networks:
  hostnet:
    external: true
    name: host
