version: "3"
services:
  rest:
    image: restimage
    environment:
      - "MONGO_USER=${MONGO_USER}"
      - "MONGO_URL=${MONGO_URL}"
      - "MONGO_PASS=${MONGO_PASS}"
      - "DOCKER_SERVER=${DOCKER_SERVER}"
    deploy:
      replicas: 1
    ports:
      - "8081:8081"

  scraper:
    image: scrimage
    environment:
      - "REST=http://rest:8081"
    depends_on:
      - "rest"
    deploy:
      replicas: 3
